name: ghostflow

on:
  #- push
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  ghostflow:
    name: ghostflow
    runs-on: ubuntu-latest
    container: benboeckel/ghostflow-github-action:wip
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Checkout PR HEAD
      # This is a hack. Doesn't work for submodule-using projects.
      # https://github.com/actions/checkout/issues/61
      run: git checkout HEAD^2
    - name: Run ghostflow
      run: /usr/local/bin/ghostflow-cli -dddd --ci github-action check run topic
      # Commented out because github rebuilds the container on each invokation
      # otherwise.
      # uses: mathstuf/ghostflow-action-sandbox@master
      # with:
      #   args: --ci github-action check run
      env:
        RUST_BACKTRACE: full
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
