name: ghostflow

on:
  - push
  - pull_request

jobs:
  ghostflow:
    name: ghostflow
    runs-on: ubuntu-latest
    container: benboeckel/ghostflow-github-action:wip
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run ghostflow
      run: /usr/local/bin/ghostflow-cli --repo "$GITHUB_WORKSPACE" check run
